import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import {Oswald} from 'next/font/google'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({ subsets: ['cyrillic-ext'] })
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={oswald.className}
        
      >
        <Provider>
          {children}
        </Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
